-- AlterTable
ALTER TABLE "DocumentoModelo" ADD COLUMN IF NOT EXISTS "logoUrl" TEXT NOT NULL DEFAULT '';
ALTER TABLE "DocumentoModelo" ADD COLUMN IF NOT EXISTS "cabecalhoHtml" TEXT NOT NULL DEFAULT '';
ALTER TABLE "DocumentoModelo" ADD COLUMN IF NOT EXISTS "rodapeHtml" TEXT NOT NULL DEFAULT '';
